@startuml
  participant Console as Console
  participant Server as Server
  collections DropOffLocations as DropOffLocations
  participant MapService as MapService
  collections Users as Users
  participant User as "u: User"
  collections Quotations as Quotations

activate Console
Console -> Server ++ : login(username, password)
Server -> Users ++ : findUser(username)
alt user found
  Users --> Server: User u
  Server --> Console: User u
  Server -> User: getPassword()
  alt correct password
    alt 
    else
    end

  else incorrect password
    Server --> Console !! : incorrectPasswordError

  end
else user not found
  Users --> Server !! : userNotFoundError
  Server --> Console !! : userNotFoundError
end
deactivate Console