@startuml classDiagram
skinparam linetype ortho



class Guest {
  + trackOrder() : ShippingStatus
}

class Client {
  + firstname : String
  + lastname : String
  + email : String
  + password : String
  + login() : void
  + createQuotation() : void
  + plateOrder(paymentInfo) : void
  - makePayment(Quotation quotation) : void
}

class Payment {
  + amount
  - cardNumber
  - cardExpirationDate
  - cardCvv
  + getCardInfo()
}

class Location {
  + streetAddress : String
  + postalCode : String
  + city : String
  + country : String
}

abstract class Origin {
  + getOriginAddress()
}

class HomePickup{}
class ScheduledHomePickup{
  + pickupTime : DateTime
  + changePickupTime(DateTime time) : void
}

class StationDropoff{
  + station : Location
  + changeStation(Location location) : void
}

class Quotation {
  + expectedDelay : Number
  + price : Number
  + someVariablewithalongname
}

class Delivery {
  + isCompleted() : Boolean
}

class ShippingStatus {
  + eta : DateTime
  + travelPath : Location[]
  - currentLocation : number
  + getCurrentLocation() : Location
  + getTravelPath() : Location[]
  + getEta() : DateTime
}


class Parcel {
  + weight : number
  + height : number
  + width : number
  + length : number
}

Guest <|-- Client
Quotation --|> Delivery
StationDropoff --|> Origin
HomePickup --|> Origin
ScheduledHomePickup --|> HomePickup

Client "1" -left- "*" Quotation : CRUD
Parcel "1" -- "1" Quotation
Location "1" - "1" Quotation : destination
Location "1" - "1" Quotation
(Client, Delivery) .. Payment
Origin .. (Quotation, Location)
Delivery "1" -right- "1" ShippingStatus


@enduml